### ISSUE TITLE
Could not load file or assembly 'System.Configuration.ConfigurationManager

### ISSUE THREAD

**Issue by Hokutosei** [pusher-community/pusher-websocket-dotnet#34]
Greetings,

I am having some issues using this lib for .netcore. here is the error. I am using a .netcore `2.0.0-preview1-005977` in macos. 

```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
```

thank you

**Comment by Mrcampbell** [comment]
Same problem!  Listening in...

**Comment by gumshoes** [comment]
.netcore does seem able to use 
```System.Configuration.ConfigurationManager```
and throws the exception you posted when it encounters it.
Look for code such as:
```
ConfigurationManager.AppSettings.Get("SomeValue")
```

**Comment by seewaage** [comment]
I'm having this same issue with .netcore 2.0 at runtime. I'm getting an error 
unhandled exception system.io.filenotfoundexception Could not load file or assembly 'System.Configuration.ConfigurationManager
I don't seem to be able to get rid of this issue even though it is compiling with no problems.
Does anyone have an idea of how to fix this?
Thanks!

**Comment by seewaage** [comment]
I fixed the problem I had. I was using the libraries that used System.Configuration.ConfigurationManager in another solution. When I used NuGet to add the System.Configuration.ConfigurationManager in the solution that called these other libraries it worked.

**Comment by masaab** [comment]
Installing Nuget package for System.Configuration.ConfigurationManager has solved the problem for us using .net core 2.0.

**Comment by Thenuwara** [comment]
My problem also solved Installing Nuget package for System.Configuration.ConfigurationManager

**Comment by mookid8000** [comment]
It makes no sense.

I can reproduce it by creating a .NET Core 2 console application. 

It makes sense that the core Rebus package can be installed, because it contains DLLs targeting .NET Standard 1.3 and .NET 4.5.

But the Rebus.AzureServiceBus package only targets .NET 4.5, which in my understanding should mean that only FULL .NET frameworks are targeted:

![image](https://user-images.githubusercontent.com/32968/35010048-e3cf6b3c-fb01-11e7-8301-2fab4caadf66.png)

But apparently it is still possible to import the package into a .NET Core 2 application, and of course it then breaks because there's no `System.Configuration` DLL available.

**Comment by mookid8000** [comment]
Hmm.... I think I might be getting closer to something now..... when you create a project for .NET Core 2, it seems to accept it when you install a NuGet package that does not target .NET Core at all.

This might be because .NET Core 2 i supposed to be compatible with .NET 4.6.1 or something, at least according to [the table on this page](https://docs.microsoft.com/en-us/dotnet/standard/net-standard).

So I went and created a new .NET Core 2 console application, and then I installed WindowsAzure.ServiceBus into it.

If I then call something on the `NamespaceManager` (pretty central entity in the Azure Service Bus driver model), I get this:
```
Unhandled Exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
   at Microsoft.ServiceBus.Messaging.Configuration.KeyValueConfigurationManager.CreateNameValueCollectionFromConnectionString(String connectionString)
   at Microsoft.ServiceBus.Messaging.Configuration.KeyValueConfigurationManager.Initialize(String connection, Nullable`1 transportType)
   at Microsoft.ServiceBus.NamespaceManager.CreateFromConnectionString(String connectionString)
   at ConsoleApp5.Program.Main() in c:\temp\ConsoleApp5\Program.cs:line 22
```

Poking around in Visual Studio, I noticed this:

![image](https://user-images.githubusercontent.com/32968/35011332-fd1f1408-fb05-11e7-91be-be9ff8a75b64.png)

which I guess is Visual Studio's way of saying "you're lucky if it works, but don't count on it".

---

Conclusion at this point: It (still) doesn't seem like the old Azure Service Bus driver supports .NET Core. This is probably also the reason why Microsoft created [the new driver](https://github.com/Azure/azure-service-bus-dotnet).

The new driver just happens to represent a huge departure from the old driver's model, both because queue and topic management can no longer be done using the driver, but also because it insists on working in a more framework-like manner (i.e. it uses callbacks to process received messages and does not support the previous poll-to-receive way of receiving messages).

If there's any way you can use the full .NET framework, I suggest you do that. Otherwise, maybe you can move your code to AWS and use Rebus with Amazon SQS – Amazon has been kind enough to port their driver to .NET Standard 1.3, making it available anywhere you can think of 😁

**Comment by kn100** [comment]
Hi all! 
This library does not officially support .NET core yet. I assume everybody experiencing this issue is trying to use it as such?

**Comment by sahil1436** [comment]
any solution for consuming compatibility package which could help in consuming framework component in .net core

**Comment by sahil1436** [comment]
please help i am facing comparability issue.

**Comment by imaji** [comment]
Hi,

If you're using the .net core you need to install the system.configuration.configurationamanger nuget package.

Best regards,
John

**Comment by Yunhan-Zheng** [comment]
Hi,
I have a .NET FX46 referencing a NET standard lib which uses Serilog. The build on my local works but on build agent does not. The error is `System.IO.FileloadException: could not load file or assembly System.Configuration.configurationManager, version=4.0.0.0, Culture=neutral, PublicKeyToken=`.... from Serilog.Settings.AppSettings. I tried adding System.Configuration.configurationManager directly to my FX project, the build still fails. I also tried adding ```
<PropertyGroup>
  <_HasReferenceToSystemRuntime>true</_HasReferenceToSystemRuntime>
</PropertyGroup>
```. No luck. Would you please help?
Thank you!

**Comment by kn100** [comment]
Hi @Yunhan-Zheng @parad74 - What error are you getting after you've added `System.Configuration.configurationManager`?

**Comment by mimogollon1** [comment]
It worked for me to add the following tag in the csproj:

<ItemGroup>
    <Reference Include="System.Configuration">
      <HintPath>..\..\..\..\..\..\..\Windows\Microsoft.NET\Framework64\v4.0.30319\System.Configuration.dll</HintPath>
    </Reference>
  </ItemGroup>

**Comment by jordi5300** [comment]
> I fixed the problem I had. I was using the libraries that used System.Configuration.ConfigurationManager in another solution. When I used NuGet to add the System.Configuration.ConfigurationManager in the solution that called these other libraries it worked.

Ty

**Comment by danielmeza** [comment]
I had the same issue, the reason was a package conflict between the same package in different project I solved by installing the same version in all my projects.

**Comment by PauloFLOAmaral** [comment]
**<ItemGroup>
    <Reference Include="System.Configuration.ConfigurationManager">
      <HintPath>C:\Users\Paulo Fernando\.nuget\packages\system.configuration.configurationmanager\4.7.0\lib\netstandard2.0\System.Configuration.ConfigurationManager.dll</HintPath>
    </Reference>
  </ItemGroup>**

Can you add a reference at your .csproj

**Comment by waqzah** [comment]
Same issue. Any solution?

`Exception while executing function: EntityPlugin <--- Could not load file or assembly 'System.Configuration.ConfigurationManager, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
`

**Comment by waqzah** [comment]
I install **Microsoft.Windows.Compatibility** NuGet but same issue.

**Comment by BalintBende** [comment]
Hello,

Same issue. Simple .net core app 2.2. 
<img width="670" alt="image" src="https://user-images.githubusercontent.com/53426892/93588269-753edf80-f9ab-11ea-8462-b11cb7b2af70.png">

I have already installed the System.Configuration.ConfigurationManager but has the following issue.
`System.IO.FileLoadException: Failed to load Xbim.Geometry.Engine64.dll ---> System.TypeInitializationException: The type initializer for '<Module>' threw an exception. ---> <CrtImplementationDetails>.ModuleLoadException: The C++ module failed to load.
 ---> System.EntryPointNotFoundException: A library name must be specified in a DllImport attribute applied to non-IJW methods.`

**Comment by synek317** [comment]
Today I've found another workaround, that works for me, but I have no idea why. At the beginning of my application (in my case - in the `[OneTimeSetUp]` of NUnit tests), I do

```
System.Reflection.Assembly.Load("System.Configuration.ConfigurationManager");
```

**Comment by itsmebhaskar** [comment]
> I fixed the problem I had. I was using the libraries that used System.Configuration.ConfigurationManager in another solution. When I used NuGet to add the System.Configuration.ConfigurationManager in the solution that called these other libraries it worked.

This fixed my problem too. Just adding nuget package to the running project.

**Comment by mohamedeshiba** [comment]
I had the same problem when I tried to connect to CosmosDb from a time triggered Azure Function. 
Here what I did to solve the problem 
1- downgraded the projecto to netcoreapp3.1 
2- Used the Azure Function V3 
3- used Microsoft.NET.Sdk.Functions version 3.1.1(any version 3) 
4- Added         <_FunctionsSkipCleanOutput>true</_FunctionsSkipCleanOutput> in the property Group tag in the .csproj 

It worked for me. Hope this helps

**Comment by masaab** [comment]
I just added Task.Delay(5000) and now it works fine
