### ISSUE TITLE
Connection to multiple channes doesn't seem working

### ISSUE THREAD

**Issue by pavel-khritonenko** [pusher-community/pusher-websocket-dotnet#52]
I use Pusher for connecting to BitStamp exchange ( https://www.bitstamp.net/websocket/ ) to get orderbooks, and it works for a single currency. If I try to connect to several channels only orderbooks from last connection arrive.

When I try to create multiple Pusher instances, it fails with the error:

```
Unhandled Exception: System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PusherClient.EventEmitter.EmitEvent(String eventName, String data)
   at PusherClient.Connection.websocket_MessageReceived(Object sender, MessageReceivedEventArgs e)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.NetSystem.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException_InvalidOperation_EnumFailedVersion()
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at PusherClient.EventEmitter.EmitEvent(String eventName, String data)
   at PusherClient.Connection.websocket_MessageReceived(Object sender, MessageReceivedEventArgs e)
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AsyncTcpSession.ProcessReceive(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted(SocketAsyncEventArgs e)
   at System.Net.Sockets.SocketAsyncEventArgs.ExecutionCallback(Object state)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.Sockets.SocketAsyncEventArgs.FinishOperationAsyncSuccess(Int32 bytesTransferred, SocketFlags flags)
   at System.Net.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.ReceiveOperation.InvokeCallback()
   at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<>c.<TryCompleteOrAbortAsync>b__14_0(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
.Sockets.SocketAsyncEventArgs.CompletionCallback(Int32 bytesTransferred, SocketFlags flags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncEventArgs.TransferCompletionCallbackCore(Int32 bytesTransferred, Byte[] socketAddress, Int32 socketAddressSize, SocketFlags receivedFlags, SocketError socketError)
   at System.Net.Sockets.SocketAsyncContext.ReceiveOperation.InvokeCallback()
   at System.Net.Sockets.SocketAsyncContext.AsyncOperation.<>c.<TryCompleteOrAbortAsync>b__14_0(Object o)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()```

**Comment by imaji** [comment]
Hi,

Is there a reason why you're creating multiple instances of Pusher?  It does handle a single instance with multiple channels registered.

I believe it was designed as a single instance mechanism.

Best regards,
John

**Comment by pavel-khritonenko** [comment]
Yes, sorry. It was a mistake in my code when I tried to use the single Pusher. All works as expected.

**Comment by imaji** [comment]
:) I'll look into fixing that anyways, it shouldn't let you do that :)
